name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '26 13 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Close Stale Issues
      uses: actions/stale@v3.0.19
      
